ARDUINO_DIR = /home/zara/arduino-1.6.5-r5
BOARD_TAG = ethernet
ARDUINO_SKETCHBOOK = ../../Arduino-Makefile
ARDMK_DIR = ../../Arduino-Makefile
AVR_TOOLS_DIR=/usr
ARDUINO_LIBS = Wire SPI EEPROM Adafruit_HTU21DF_Library Adafruit_MCP9808_Library SparkFun_SX1509_Arduino_Library Ethernet Adafruit_SleepyDog
#AVRDUDE = /usr/bin/avrdude
include ../Arduino.mk
#ARDUINO_PORT = /dev/ttyUSB0
#ARDUINO_SKETCHBOOK = /home/zuhraa470/monitor-control/arduino-mk
#ARDUINO_LIB_PATH = /home/zuhraa470/monitor-control/arduino-mk/libraries
